blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.autodiscover()
admin.site.enable_nav_sidebar = False

main/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='main'

urlpatterns = [
    path('',views.HomepageView.as_view(),name="home"),
    path('theme/<slug:theme_slug>/',views.ThemeView,name="theme"),
    path('theme/<slug:theme_slug>/<slug:post_slug>/',views.PostView,name="post"),
    path('add_theme/',views.ThemeCreateView.as_view(),name='add_theme'),
    path('add_post/',views.PostCreateView.as_view(),name='add_post'),
    path('theme/<slug:theme_slug>/<slug:post_slug>/leave_comment',views.leave_comment,name="leave_comment"),
    path('<int:pk>/delete-comment/',views.CommentDeleteView.as_view(),name='delete_comment'),
    path('<int:pk>/delete-theme/',views.ThemeDeleteView.as_view(),name='delete_theme'),
    path('<int:pk>/delete-post/',views.PostDeleteView.as_view(),name='delete_post'),
    path('<int:pk>/update-theme/',views.ThemeUpdateView.as_view(),name='update_theme'),
    path('<int:pk>/update-post/',views.PostUpdateView.as_view(),name='update_post'),
    path('<slug:theme_slug>/add_post/',views.PostCreateView2.as_view(),name='add_post2')

]
#«Блять, забыл рансервер запустить, охуенно» ©️Хауди

main/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils.text import slugify
from django.contrib.auth.models import User
from imagekit.models import ImageSpecField
from pilkit.processors import ResizeToFill

class theme(models.Model):
    name = models.CharField(max_length=250)
    theme_slug = models.SlugField(max_length=255,default='')

    def __str__(self):
        return self.name

    def save(self, *args,**kwargs):
        self.theme_slug = slugify(self.name)
        super().save(*args,**kwargs)

class post(models.Model):
    theme = models.ForeignKey(theme,on_delete=models.CASCADE)
    post_views=models.IntegerField(default=0)
    name = models.CharField(max_length=250)
    post_slug = models.SlugField(max_length=255,default='')
    description = models.TextField()
    Img = models.ImageField(upload_to='photos')
    Img2 = models.ImageField(upload_to='photos',blank=True)
    Img3 = models.ImageField(upload_to='photos',blank=True)
    Img4 = models.ImageField(upload_to='photos',blank=True)
    Img5 = models.ImageField(upload_to='photos',blank=True)
    Img6 = models.ImageField(upload_to='photos',blank=True)
    Img7 = models.ImageField(upload_to='photos',blank=True)
    Img8 = models.ImageField(upload_to='photos',blank=True)
    Img9 = models.ImageField(upload_to='photos',blank=True)
    Img10 = models.ImageField(upload_to='photos',blank=True)
    video = models.FileField(upload_to='videos',validators=[FileExtensionValidator(allowed_extensions=['mp4'])],blank=True)
    file = models.FileField(upload_to='files',blank=True)
    audio = models.FileField(upload_to='audio',blank=True,validators=[FileExtensionValidator(allowed_extensions=['mp3'])])
    link = models.URLField(max_length=5000,blank=True)

    image_medium = ImageSpecField(source='Img',processors=[ResizeToFill(220,220)]
    ,format='JPEG',options={'quality': 60})

    def __str__(self):
        return self.name

    def save(self, *args,**kwargs):
        self.post_slug = slugify(self.name)+ "-" + str(self.theme.theme_slug)
        super().save(*args,**kwargs)

class comment (models.Model):
    post = models.ForeignKey(post,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    text = models.TextField()

main/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views.generic import TemplateView,DetailView,ListView,View
from .models import theme,post,comment
from django.contrib.auth.mixins import PermissionRequiredMixin,LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy,reverse
from django.http import Http404,HttpResponseRedirect
from django.views.generic.edit import CreateView, DeleteView, UpdateView
# Create your views here.

class RedirectToPreviousMixin:

    default_redirect = '/'

    def get(self, request, *args, **kwargs):
        request.session['previous_page'] = request.META.get('HTTP_REFERER', self.default_redirect)
        return super().get(request, *args, **kwargs)

    def get_success_url(self):
        return self.request.session['previous_page']


class HomepageView(ListView):
    template_name='main/home/index.html'
    context_object_name ='themes'
    def get_queryset(self):
        q = self.request.GET.get('q')
        if q and q != '':
            return theme.objects.filter(name__icontains=q)
        else:
            return theme.objects.order_by('name')


def ThemeView(request,theme_slug):
    t=theme.objects.get(theme_slug=theme_slug)
    p = t.post_set.order_by('-id')
    context={
        'theme': t ,
        'posts':p
    }
    return render(request, 'main/home/theme.html',context)


def PostView(request,post_slug,theme_slug):
    p=post.objects.get(post_slug=post_slug)
    t=theme.objects.get(theme_slug=theme_slug)
    p.post_views=p.post_views+1
    p.save()
    c = p.comment_set.order_by('-id')
    context={
        'theme':t,
        'post':p ,
        'comments':c,

    }
    return render(request, 'main/home/post.html',context)

class ThemeCreateView(PermissionRequiredMixin,SuccessMessageMixin,CreateView,):
    model = theme
    action = 'add theme'
    fields = ['name']
    success_url = reverse_lazy('main:home')
    permission_required = 'main.add_theme'
    success_message = '"%(name)s" was created successfully'

class PostCreateView(PermissionRequiredMixin,SuccessMessageMixin,CreateView,):
    model = post
    action = 'add post to theme'
    fields = ['theme','name','description','link','file','video','audio','Img','Img2','Img3','Img4'
    ,'Img5','Img6','Img7','Img8','Img9','Img10']
    success_url = reverse_lazy('main:home')
    permission_required = 'main.add_post'
    success_message = '"%(name)s" was created successfully'

class PostCreateView2(PermissionRequiredMixin,SuccessMessageMixin,CreateView,):
    model = post
    action = 'add post to theme'
    fields = ['name','description','link','file','video','audio','Img','Img2','Img3','Img4'
    ,'Img5','Img6','Img7','Img8','Img9','Img10']
    success_url = reverse_lazy('main:home')
    permission_required = 'main.add_post'
    success_message = '"%(name)s" was created successfully'

    def form_valid(self, form):
        t = get_object_or_404(theme, theme_slug=self.kwargs['theme_slug'])
        form.instance.theme = t
        return super(PostCreateView2, self).form_valid(form)


class PostUpdateView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView,):
    model = post
    action = 'edit post'
    fields = ['theme','name','description','link','file','video','audio','Img','Img2','Img3','Img4'
    ,'Img5','Img6','Img7','Img8','Img9','Img10']
    success_url = reverse_lazy('main:home')
    permission_required = 'main.add_post'
    success_message = '"%(name)s" was created successfully'

class ThemeUpdateView(PermissionRequiredMixin,SuccessMessageMixin,UpdateView,):
    model = theme
    action = 'edit theme'
    fields = ['name']
    success_url = reverse_lazy('main:home')
    permission_required = 'main.add_theme'
    success_message = '"%(name)s" was created successfully'

def leave_comment(request,post_slug,theme_slug):
    p=post.objects.get(post_slug=post_slug)
    t=theme.objects.get(theme_slug=theme_slug)
    p.comment_set.create(user = request.user, text = request.POST['TEXT'] )

    return HttpResponseRedirect( reverse('main:post',args=(t.theme_slug,p.post_slug) ) )

class CommentDeleteView(RedirectToPreviousMixin,DeleteView):
    model = comment
    action = 'delete comment'

class ThemeDeleteView(DeleteView):
    model = theme
    action = 'delete theme'
    success_url = reverse_lazy('main:home')

class PostDeleteView(DeleteView):
    model = post
    action = 'delete post'
    success_url = reverse_lazy('main:home')

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/site.css' %}?{% now "U" %}">
    {% block head %}
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            {% if not user.is_authenticated  %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">login</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'account_logout' %}">logout</a>
              </li>
            {% endif %}
            {% if user.is_superuser %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  admin
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                  <li><a class="dropdown-item" href="{% url 'admin:login' %}">admin</a></li>
                  <li><a class="dropdown-item" href="{% url 'main:add_theme' %}">add theme</a></li>
                  <li><a class="dropdown-item" href="{% url 'main:add_post' %}">add post</a></li>
                </ul>
              </li>
            {% endif %}
          </ul>
        </div>
      </div>
    </nav>
      {% block content %}
      {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
  </body>
</html>

templates/main/comment_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{view.action}}{% endblock %}
{% block content %}
<div class="container mt-3">
  <form action="." method="post">
    {% csrf_token %}

    <p>are you sure to delete "{{object}}"?</p>

    <input class="btn btn-danger" type="submit" value="confirm">

    <a href="{% url 'main:home' %}">
    <button type="button" name="button" class="btn btn-outline-secondary btn-light">cancel</button>
    </a>
  </form>

</div>

{% endblock %}

templates/main/home/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="container">
    <div class="list-group mt-3">
      {% for theme in themes %}
        <a href="{% url 'main:theme' theme.theme_slug %}" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action bg-dark">{{theme.name}}
          <span class="badge bg-primary rounded-pill">posts:{{theme.post_set.all|length}}</span></a>
      {% endfor %}
    </div>
  </div>
{% endblock %}

templates/main/home/post.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/post.css' %}?{% now 'U' %}">
{% endblock %}
{% block content %}
{% if user.is_superuser %}
  <div class="dropdown">
    <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
      admin
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
      <li><a  href="{% url 'main:delete_post' post.pk %}"class="dropdown-item">delete</a></li>
      <li><a href="{% url 'main:update_post' post.pk %}"class="dropdown-item">edit</a></li>
    </ul>
  </div>
{% endif %}
  <div class="container mt-3">
    <div class="card text-white bg-dark mb-3">
      <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel" data-bs-interval="false">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img src="{{post.Img.url}}" class="d-block w-100" alt="{{post.Img.url}}">
          </div>
          {% if post.Img2 %}
            <div class="carousel-item">
              <img src="{{post.Img2.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img3 %}
            <div class="carousel-item">
              <img src="{{post.Img3.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img4 %}
            <div class="carousel-item">
              <img src="{{post.Img4.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img5 %}
            <div class="carousel-item">
              <img src="{{post.Img5.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img6 %}
            <div class="carousel-item">
              <img src="{{post.Img6.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img7 %}
            <div class="carousel-item">
              <img src="{{post.Img7.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img8 %}
            <div class="carousel-item">
              <img src="{{post.Img8.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img9 %}
            <div class="carousel-item">
              <img src="{{post.Img9.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.Img10 %}
            <div class="carousel-item">
              <img src="{{post.Img10.url}}" class="d-block w-100" alt="{{post.Img.url}}">
            </div>
          {% endif %}
          {% if post.video %}
            <div class="carousel-item">
              <video controls class="post_video" >
                <source src="{{post.video.url}}" type="video/mp4" >
              </video>
            </div>
          {% endif %}
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls"  data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>
      <div class="card-body">
        <h1 class="card-title">{{post.name}}</h1>
        <p class="card-text">{{post.description}}</p>
        {% if post.link %}
          <div style="margin: 5px;">
              <a href="{{post.link}}" target="_blank" >{{post.link}}</a>
          </div>
        {% endif %}
        {% if post.audio %}
          <audio controls>
            <source src="{{post.audio.url}}" type="audio/mpeg">
          </audio>
        {% endif %}
        {% if post.file %}
          <a href="{{post.file.url}}" download>Download</a>
        {% endif %}
        <hr>
        {% if user.is_authenticated %}
        <form class="" action="{% url 'main:leave_comment' theme.theme_slug  post.post_slug %}" method="post">
          {% csrf_token %}
          <textarea name="TEXT" rows="8" cols="80"></textarea>
          <button type="submit" name="button" class="leave_comment">leave comment
          </button>
        </form>
        {% else %}
         to leave comment you must login
        {% endif %}
        <hr>
        <ul class="list-group mt-3">
          {% if comments %}
            {% for c in comments %}
              <li class="list-group-item d-flex justify-content-between align-items-center list-group-item-action bg-dark" id="pizdanutiis_class">{{c.user}}:    {{c.text}}
                {% if user == c.user %}
                  <a href="{% url 'main:delete_comment' c.pk %}">
                    <button type="button" class="btn btn-sm btn-outline-secondary">delete</button>
                  </a>
                {% elif user.is_superuser %}

                  <a href="{% url 'main:delete_comment' c.pk %}">
                    <button type="button" class="btn btn-sm btn-outline-secondary">delete</button>
                  </a>
                {% endif %}
              </li>
            {% endfor %}
          {% else %}
            no comments found
          {% endif %}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

templates/main/home/theme.html
{% extends 'base.html' %}
{% load static %}
{% block head %}
  <link rel="stylesheet" href="{% static 'css/theme.css' %}?{% now 'U' %}">
{% endblock %}
{% block content %}

    {% if user.is_superuser %}
      <div class="dropdown">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          admin
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <li><a class="dropdown-item" href="{% url 'main:delete_theme' theme.pk %}">delete_theme</a></li>
          <li><a class="dropdown-item" href="{% url 'main:update_theme' theme.pk %}">edit_theme</a></li>
          <li><a class="dropdown-item" href="{% url 'main:add_post2' theme.theme_slug %}">add_post</a></li>

        </ul>
      </div>
    {% endif %}
    <div class="container mt-3 ">
      {% if posts %}

          {% for p in posts %}
            <div class="card text-white bg-dark mb-3"  >
              <img src="{{p.image_medium.url}}" class="card-img-top" alt="image here"  >
              <div class="card-body">
                <h5 class="card-title">{{p.name}} <span class="badge rounded-pill bg-primary">views:{{p.post_views}}</span></h5>
                <a href="{% url 'main:post' theme.theme_slug  p.post_slug   %}" class="btn btn-outline-light">view</a>
                {% if user.is_superuser %}
                  <a href="{% url 'main:delete_post' p.pk  %}" class="btn btn-outline-light">delete</a>
                  <a href="{% url 'main:update_post' p.pk  %}" class="btn btn-outline-light">edit</a>
                {% endif %}
              </div>
            </div>
          {% endfor %}
        {% else %}
          no posts found

      {% endif %}
    </div>

{% endblock %}

templates/main/post_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{view.action}}{% endblock %}
{% block content %}
<div class="container mt-3">
  <form action="." method="post">
    {% csrf_token %}

    <p>are you sure to delete "{{object}}"?</p>

    <input class="btn btn-danger" type="submit" value="confirm">

    <a href="{% url 'main:home' %}">
    <button type="button" name="button" class="btn btn-outline-secondary btn-light">cancel</button>
    </a>
  </form>

</div>

{% endblock %}

templates/main/post_form.html
{% extends 'base.html' %}
{% block title %}{{view.action}}{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="container mt-3">
  <h1>{{view.action}}</h1>
  <form method="post" action="." enctype="multipart/form-data">

    {% csrf_token %}
    {{form|crispy}}


      <input class="btn btn-outline-secondary btn-light mt-3" type="submit" value="confirm">
    <a href="{% url 'main:home' %}">
      <button type="button" name="button" class="btn btn-outline-secondary btn-light mt-3">cancel</button>
    </a>

  </form>

</div>
{% endblock %}

templates/main/text_form.html
{% extends 'base.html' %}
{% block title %}{{view.action}}{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="container mt-3">
  <h1>{{view.action}}</h1>
  <form method="post" action="." enctype="multipart/form-data">

    {% csrf_token %}
    {{form|crispy}}


      <input class="btn btn-outline-secondary btn-light mt-3" type="submit" value="confirm">
    <a href="{% url 'main:home' %}">
      <button type="button" name="button" class="btn btn-outline-secondary btn-light mt-3">atcelt</button>
    </a>

  </form>

</div>
{% endblock %}

templates/main/theme_confirm_delete.html
{% extends 'base.html' %}
{% block title %}{{view.action}}{% endblock %}
{% block content %}
<div class="container mt-3">
  <form action="." method="post">
    {% csrf_token %}

    <p>are you sure to delete "{{object}}"?</p>

    <input class="btn btn-danger" type="submit" value="confirm">

    <a href="{% url 'main:home' %}">
    <button type="button" name="button" class="btn btn-outline-secondary btn-light">cancel</button>
    </a>
  </form>

</div>

{% endblock %}

templates/main/theme_form.html
{% extends 'base.html' %}
{% block title %}{{view.action}}{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="container mt-3">
  <h1>{{view.action}}</h1>
  <form method="post" action="." enctype="multipart/form-data">

    {% csrf_token %}
    {{form|crispy}}


      <input class="btn btn-outline-secondary btn-light mt-3" type="submit" value="confirm">
    <a href="{% url 'main:home' %}">
      <button type="button" name="button" class="btn btn-outline-secondary btn-light mt-3">cancel</button>
    </a>

  </form>

</div>
{% endblock %}